// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Checkboxes = __t.object("Checkboxes", {
  idx: __t.u32(),
  boxes: __t.byteArray(),
});
export type Checkboxes = __Infer<typeof Checkboxes>;

export const PoisonJob = __t.object("PoisonJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PoisonJob = __Infer<typeof PoisonJob>;

export const Stats = __t.object("Stats", {
  id: __t.u32(),
  totalColored: __t.u64(),
});
export type Stats = __Infer<typeof Stats>;

export const SyncStatsJob = __t.object("SyncStatsJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SyncStatsJob = __Infer<typeof SyncStatsJob>;

