// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CheckboxChanges = __t.object("CheckboxChanges", {
  id: __t.u64(),
  documentIdx: __t.u32(),
  arrayIdx: __t.u32(),
  color: __t.u32(),
  createdAt: __t.u64(),
});
export type CheckboxChanges = __Infer<typeof CheckboxChanges>;

export const CheckboxSync = __t.object("CheckboxSync", {
  id: __t.u32(),
  latestChangeId: __t.u64(),
});
export type CheckboxSync = __Infer<typeof CheckboxSync>;

export const Checkboxes = __t.object("Checkboxes", {
  idx: __t.u32(),
  boxes: __t.byteArray(),
});
export type Checkboxes = __Infer<typeof Checkboxes>;

export const FingerprintRateLimit = __t.object("FingerprintRateLimit", {
  fingerprint: __t.string(),
  lastToggleAt: __t.u64(),
  toggleCount: __t.u32(),
});
export type FingerprintRateLimit = __Infer<typeof FingerprintRateLimit>;

export const GolBootstrap = __t.object("GolBootstrap", {
  id: __t.u32(),
  cells: __t.byteArray(),
  version: __t.u64(),
  generation: __t.u64(),
});
export type GolBootstrap = __Infer<typeof GolBootstrap>;

export const GolDiff = __t.object("GolDiff", {
  id: __t.u32(),
  data: __t.byteArray(),
});
export type GolDiff = __Infer<typeof GolDiff>;

export const GolDiffLog = __t.object("GolDiffLog", {
  version: __t.u64(),
  data: __t.byteArray(),
});
export type GolDiffLog = __Infer<typeof GolDiffLog>;

export const GolDiffV2 = __t.object("GolDiffV2", {
  id: __t.u32(),
  version: __t.u64(),
  data: __t.byteArray(),
});
export type GolDiffV2 = __Infer<typeof GolDiffV2>;

export const GolGrid = __t.object("GolGrid", {
  id: __t.u32(),
  cells: __t.byteArray(),
  generation: __t.u64(),
});
export type GolGrid = __Infer<typeof GolGrid>;

export const GolLoopStatus = __t.object("GolLoopStatus", {
  id: __t.u32(),
  loopPeriod: __t.u32(),
});
export type GolLoopStatus = __Infer<typeof GolLoopStatus>;

export const GolMeta = __t.object("GolMeta", {
  id: __t.u32(),
  generation: __t.u64(),
});
export type GolMeta = __Infer<typeof GolMeta>;

export const GolRowChunk = __t.object("GolRowChunk", {
  rowIdx: __t.u32(),
  cells: __t.byteArray(),
});
export type GolRowChunk = __Infer<typeof GolRowChunk>;

export const GolSync = __t.object("GolSync", {
  id: __t.u32(),
  version: __t.u64(),
  generation: __t.u64(),
});
export type GolSync = __Infer<typeof GolSync>;

export const GolTickJob = __t.object("GolTickJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GolTickJob = __Infer<typeof GolTickJob>;

export const IdentityFingerprint = __t.object("IdentityFingerprint", {
  identity: __t.identity(),
  fingerprint: __t.string(),
});
export type IdentityFingerprint = __Infer<typeof IdentityFingerprint>;

export const PruneChangesJob = __t.object("PruneChangesJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PruneChangesJob = __Infer<typeof PruneChangesJob>;

export const RateLimit = __t.object("RateLimit", {
  identity: __t.identity(),
  lastToggleAt: __t.u64(),
  toggleCount: __t.u32(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Stats = __t.object("Stats", {
  id: __t.u32(),
  totalColored: __t.u64(),
});
export type Stats = __Infer<typeof Stats>;

export const SyncStatsJob = __t.object("SyncStatsJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SyncStatsJob = __Infer<typeof SyncStatsJob>;

