// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Checkboxes = __t.object("Checkboxes", {
  idx: __t.u32(),
  boxes: __t.byteArray(),
});
export type Checkboxes = __Infer<typeof Checkboxes>;

export const FingerprintRateLimit = __t.object("FingerprintRateLimit", {
  fingerprint: __t.string(),
  lastToggleAt: __t.u64(),
  toggleCount: __t.u32(),
});
export type FingerprintRateLimit = __Infer<typeof FingerprintRateLimit>;

export const GolGrid = __t.object("GolGrid", {
  id: __t.u32(),
  cells: __t.byteArray(),
  generation: __t.u64(),
});
export type GolGrid = __Infer<typeof GolGrid>;

export const GolTickJob = __t.object("GolTickJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GolTickJob = __Infer<typeof GolTickJob>;

export const IdentityFingerprint = __t.object("IdentityFingerprint", {
  identity: __t.identity(),
  fingerprint: __t.string(),
});
export type IdentityFingerprint = __Infer<typeof IdentityFingerprint>;

export const RateLimit = __t.object("RateLimit", {
  identity: __t.identity(),
  lastToggleAt: __t.u64(),
  toggleCount: __t.u32(),
});
export type RateLimit = __Infer<typeof RateLimit>;

export const Stats = __t.object("Stats", {
  id: __t.u32(),
  totalColored: __t.u64(),
});
export type Stats = __Infer<typeof Stats>;

export const SyncStatsJob = __t.object("SyncStatsJob", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type SyncStatsJob = __Infer<typeof SyncStatsJob>;

