// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import SeedReducer from "../seed_reducer";
import ToggleReducer from "../toggle_reducer";

export type SeedParams = __Infer<typeof SeedReducer>;
export type ToggleParams = __Infer<typeof ToggleReducer>;

