// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import RegisterFingerprintReducer from "../register_fingerprint_reducer";
import SeedReducer from "../seed_reducer";
import SyncStatsReducer from "../sync_stats_reducer";
import ToggleReducer from "../toggle_reducer";

export type RegisterFingerprintParams = __Infer<typeof RegisterFingerprintReducer>;
export type SeedParams = __Infer<typeof SeedReducer>;
export type SyncStatsParams = __Infer<typeof SyncStatsReducer>;
export type ToggleParams = __Infer<typeof ToggleReducer>;

